branches:
  except:
    - /travis-.*/

before_build:
  - nuget restore nunit.sln

build_script: 
  - ps: |
      .\appveyor.ps1
      if ($lastexitcode -ne 0){ exit $lastexitcode }
  
#test_script:
#  - msbuild NUnit.proj /t:TestAll /p:Configuration=Release /p:ResultFormat=nunit2 /p:ContinueOnFailure=ErrorAndContinue
#  - ps: $wc = New-Object 'System.Net.WebClient'
#  - ps: $dir = "bin\Release\Results"
#  - ps: $uri = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)"
#  - ps: foreach($item in (dir $dir "*.xml")) { $wc.UploadFile($uri, $item.FullName) }
  
artifacts:
- path: package\*.nupkg
- path: package\*.msi

version: '{build}'